parameters:
    flamingo.manager.command.instance.class:      Earls\FlamingoCommandQueueBundle\Model\CommandManagerInstance
    flamingo.manager.command.factory.class:       Earls\FlamingoCommandQueueBundle\Model\CommandManagerInstanceFactory
    flamingo.execution.control.class:             Earls\FlamingoCommandQueueBundle\Model\ExecutionControl
    flamingo.stopwatch.class:                     Earls\FlamingoCommandQueueBundle\Model\Stopwatch

services:
    flamingo.stopwatch:
        class:  %flamingo.stopwatch.class%

    flamingo.execution.control:
        class:  %flamingo.execution.control.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    flamingo.manager.command:
        class:  %flamingo.manager.command.instance.class%
        factory_class:  "%flamingo.manager.command.factory.class%"
        factory_method: get
        scope: prototype
        arguments:
            - "@flamingo.stopwatch"
            - "@flamingo.execution.control"
            - "@doctrine.orm.entity_manager"        
