parameters:
    flamingo.manager.command.instance.class:      Earls\FlamingoCommandQueueBundle\Model\CommandManagerInstance
    flamingo.manager.command.factory.class:       Earls\FlamingoCommandQueueBundle\Model\CommandManagerInstanceFactory
    flamingo.manager.log.class:                   Earls\FlamingoCommandQueueBundle\Manager\LogManager
    
    flamingo.execution.control.class:             Earls\FlamingoCommandQueueBundle\Model\ExecutionControl
    flamingo.stopwatch.class:                     Earls\FlamingoCommandQueueBundle\Model\Stopwatch
    flamingo.admin.template:                      "EarlsFlamingoCommandQueueBundle::layout.html.twig"
    flamingo.log.save.limit:                      20000
    flamingo.log.save.status:                     "NOTICE"
    
services:
    flamingo.stopwatch:
        class:  %flamingo.stopwatch.class%
    
    flamingo.manager.log:
        class: "%flamingo.manager.log.class%"

    flamingo.execution.control:
        class:  %flamingo.execution.control.class%
        arguments:
            - "@doctrine.orm.entity_manager"   
            - "%flamingo.log.save.limit%"
            - "%flamingo.log.save.status%"
            - "@flamingo.manager.log"

    flamingo.manager.command:
        class:  %flamingo.manager.command.instance.class%
        factory_class:  "%flamingo.manager.command.factory.class%"
        factory_method: get
        scope: prototype
        arguments:
            - "@flamingo.stopwatch"
            - "@flamingo.execution.control"
            - "@doctrine.orm.entity_manager" 
      
    

  