parameters:
    flamingo.manager.command.class:     Earls\FlamingoCommandQueueBundle\Manager\CommandManager
    flamingo.execution.control.class:   Earls\FlamingoCommandQueueBundle\Manager\ExecutionControl
    flamingo.stopwatch.class:           Earls\FlamingoCommandQueueBundle\Model\Stopwatch

services:
    flamingo.stopwatch:
        class:  %flamingo.stopwatch.class%

    flamingo.execution.control:
        class:  %flamingo.execution.control.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    flamingo.manager.command:
        class:  %flamingo.manager.command.class%
        arguments:
            - "@flamingo.stopwatch"
            - "@flamingo.execution.control"
            - "@doctrine.orm.entity_manager"
