sudo: false
language:
    - php
php:
    - "5.5"
# env:
#     - ACTION="composer run lint"
#     - ACTION="composer run test"
    
before_script:
    - composer install
  
script:
    - composer run lint
    - composer run test
    
after_success:
    - composer run coverall
    
notifications:
    email:
        -  cifren@msn.com