sudo: false
language:
    - php
php:
    - "5.5"
env:
    - ACTION="composer run lint"
    - ACTION="composer run test ; composer run coverall"
    
before_script:
    - phpenv config-rm xdebug.ini
    - composer install
  
script:
    - $ACTION
    
notifications:
    email:
        -  cifren@msn.com